file_read = open('PYTHON\Codingal.txt', 'r')
print("File in Read Mode -")
print(file_read.read())
file_read.close()
file_write = open('PYTHON\Codingal.txt', 'w')
file_write.write("File in Write Mode....")
file_write.write("Hi! I am Penguin. I am 1 yr. old.")
file_write.close()
file_append = open('PYTHON\Codingal.txt', 'a')
file_append.write("\nFile in append Mode....")
file_append.write("Hi! I am Penguin. I am 1 yr. old.")
file_append.close()